export const getImageByCharacter = {
  A: "/img/letter-A-American-Sign-Language-ASL.webp",
  B: "/img/letter-B-American-Sign-Language-ASL.webp",
  C: "/img/letter-C-American-Sign-Language-ASL.webp",
  D: "/img/letter-D-American-Sign-Language-ASL.webp",
  E: "/img/letter-E-American-Sign-Language-ASL.webp",
  F: "/img/letter-F-American-Sign-Language-ASL.webp",
  G: "/img/letter-G-American-Sign-Language-ASL.webp",
  H: "/img/letter-H-American-Sign-Language-ASL.webp",
  I: "/img/letter-I-American-Sign-Language-ASL.webp",
  J: "/img/letter-J-American-Sign-Language-ASL.webp",
  K: "/img/letter-K-American-Sign-Language-ASL.webp",
  L: "/img/letter-L-American-Sign-Language-ASL.webp",
  M: "/img/letter-M-American-Sign-Language-ASL.webp",
  N: "/img/letter-N-American-Sign-Language-ASL.webp",
  O: "/img/letter-O-American-Sign-Language-ASL.webp",
  P: "/img/letter-P-American-Sign-Language-ASL.webp",
  Q: "/img/letter-Q-American-Sign-Language-ASL.webp",
  R: "/img/letter-R-American-Sign-Language-ASL.webp",
  S: "/img/letter-S-American-Sign-Language-ASL.webp",
  T: "/img/letter-T-American-Sign-Language-ASL.webp",
  U: "/img/letter-U-American-Sign-Language-ASL.webp",
  V: "/img/letter-V-American-Sign-Language-ASL.webp",
  W: "/img/letter-W-American-Sign-Language-ASL.webp",
  X: "/img/letter-X-American-Sign-Language-ASL.webp",
  Y: "/img/letter-Y-American-Sign-Language-ASL.webp",
  Z: "/img/letter-Z-American-Sign-Language-ASL.webp",
};
